### ISSUE TITLE
Make main locale configurable

### ISSUE THREAD

**Issue by goranluledzija** [localizely/flutter-intl-vscode#1]
Currently, Flutter Intl extension uses `en` as the main locale.
According to that main locale it generates Dart code and enables autocomplete.

Teams that don't develop app for the English speaking market would like to have such main locale changeable to some other locale, like `es` or `de_DE`.

**Comment by antoine-souesme-needone** [comment]
Any updates ?

**Comment by aleksakrstic** [comment]
Hi @antoine-souesme-needone 

It is planned for 15th February.

**Comment by antoine-souesme-needone** [comment]
@aleksakrstic Hi !
Thank you for your response, looking forward to this !

Cheers

**Comment by aleksakrstic** [comment]
This is now released with extension version `1.3.0`.
You can change main locale for instance to `de_DE` with the following config in `pubspec.yaml`:
```
flutter_intl:
    enabled: true
    main_locale: de_DE
```

@antoine-souesme-needone Would like to hear you feedback. 
Will leave this issue open for 2 more days.

**Comment by antoine-souesme-needone** [comment]
@aleksakrstic 
It looks like it works perfectly, thank you very much !
