### ISSUE TITLE
Can't add locale es_419 via command palette

### ISSUE THREAD

**Issue by ColinSchmale** [localizely/flutter-intl-vscode#100]
es_419 (Spanish appropriate for the Latin America and Caribbean region) seems to be a valid locale for Flutter apps but it's not possible to add it via the VS Code plugin.

The warning says "Invalid locale provided".

http://www.unicode.org/reports/tr35/

I thought I could just create an intl_es_419.arb file but this doesn't work.

That's what intl generates for es-419 if I create the .arb file manually:
`Locale.fromSubtags(languageCode: 'es'),`

Here someone said that intl can handle es-419:
https://github.com/flutter/flutter/issues/855

Flutter mentions es_419 here:
https://api.flutter.dev/flutter/dart-ui/Locale/toLanguageTag.html

It seems to me that it's possible to use es-419 with Flutter and intl but I don't understand how.

**Comment by ColinSchmale** [comment]
I thought I could just create an intl_es_419.arb file but this doesn't work.

That's what intl generates for es-419 if I create the .arb file manually:
`Locale.fromSubtags(languageCode: 'es'),`

Here someone said that intl can handle es-419:
https://github.com/flutter/flutter/issues/855

Flutter mentions es_419 here:
https://api.flutter.dev/flutter/dart-ui/Locale/toLanguageTag.html

It seems to me that it's possible to use es-419 with Flutter and intl but I don't understand how.

**Comment by lzoran** [comment]
The `Flutter Intl` extension for `VS Code` has been updated in the latest release to support locale codes based on `ISO 639-2/3` languages and `UN-M49` regions. 

I'm closing this issue now as resolved. 
If any problems arise, feel free to reopen this issue or create a new one.
