### ISSUE TITLE
problem with flutter 3.7 

### ISSUE THREAD

**Issue by shehabmohamed0** [localizely/flutter-intl-vscode#101]
this is the output produced by extension

Failed to build intl_utils:generate:
../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/backends/memory/memory_file.dart:57:8: Error: The method 'MemoryFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) {
       ^
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/backends/memory/memory_file.dart:57:8: Error: The method 'MemoryFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) {
       ^
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^

**Comment by bilalsammour** [comment]
I have the same issue.

**Comment by lzoran** [comment]
Hi @shehabmohamed0, @bilalsammour,

Everything works fine with Flutter 3.7 on my machine. 😕 

There are some known cache issues after upgrading Flutter.
Could you check if reactivating the `intl_utils` package helps? 

Steps:
1. Deactivate `intl_utils` package: `flutter pub global deactivate intl_utils`
2. Update one of your arb files and save to trigger generation

**Comment by shehabmohamed0** [comment]
Thanks, this solves the problem.

**Comment by bilalsammour** [comment]
Works for me as well, thank you.

**Comment by Vafin84** [comment]
Does not work with flutter v3.7.1

**Comment by Vafin84** [comment]
> Does not work with flutter v3.7.1

`flutter pub global deactivate intl_utils`  solves the problem
