### ISSUE TITLE
How to get to prompts before context is available

### ISSUE THREAD

**Issue by electraport** [localizely/flutter-intl-vscode#102]
Hello, 

I have a question about this plugin. It seems like having installed and used it, there is now no way to get to a prompt before context is available or to make a placeholder for it. Is there any way to set placeholders for prompts in code that runs before a BuildContext is available?

**Comment by lzoran** [comment]
Not sure if I understand the problem well. 😕

In case you are looking for a way to use a localization message in a `MaterialApp` where you do not have access to `BuildContext`, the following example might be of help.

```
MaterialApp(
    localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
    ],
    supportedLocales: S.delegate.supportedLocales,
    onGenerateTitle: (BuildContext context) => S.of(context).title,
    home: Builder(builder: (BuildContext context) => HomePage(title: S.of(context).pageHomeTitle)),
),
```
