### ISSUE TITLE
Add functionality to use localizations without context

### ISSUE THREAD

**Issue by josefwilhelm** [localizely/flutter-intl-vscode#11]
First of all thanks for the great plugin! 

I used to use this plugin https://github.com/long1eu/flutter_i18n

and there was an option to use the translations like this
`final title = Strings.current.title;`
More info here:
https://github.com/flutter/flutter/issues/14518

Is it possible to add this feature?

**Comment by aleksakrstic** [comment]
Hi @josefwilhelm 
Thanks for reporting this!

It is already in the roadmap for the plugin, but anyway it helps us to prioritize the work.

**Comment by fy5220** [comment]
also need this feature

**Comment by talatkuyuk** [comment]
Also, I need this feature because I want to use localization in also viewmodel file (forexample in class extends changenotifier etc.) which has no context.

**Comment by aleksakrstic** [comment]
@josefwilhelm 
This is now available in version `1.9.0`.

You can access the keys without passing `context`, for example:

    S.current.title

**Comment by badihi** [comment]
I'm using version `1.9.1` and I do not get it. Is it removed?

**Comment by badihi** [comment]
I found out that this feature has nothing to do with the version of this plugin, and is related to `intl_utils`. I had an old version and the plugin was not trying to update that.

**Comment by aleksakrstic** [comment]
Hi @badihi 
IDE plugin uses globally installed `intl_utils` and enforces its version for global installation.
For local installations of `intl_utils` via `pubspec.yaml` file, ie for CLI usage, please ensure you use the same intl_utils version as the IDE plugin. Just in case
