### ISSUE TITLE
Auto Save does not work in Flutter 3.13.1 version

### ISSUE THREAD

**Issue by denizmatsuri** [localizely/flutter-intl-vscode#111]
Auto Save does not work in Flutter 3.13.0~1 version. Does anyone have the same symptoms?

When saving the "/l10n/.arb" file, the file "/generated/intl/messages/" is not automatically generated

**Comment by lzoran** [comment]
Hi @keemeesuu,

Could you check if you have any errors within 'OUTPUT' view for the 'Flutter Intl'?

![image](https://github.com/localizely/flutter-intl-vscode/assets/15170421/cf80817a-3a08-4f96-92ac-38ec841d8aaa)


If not, could you check if reactivating the `intl_utils` package helps?
```
flutter pub global deactivate intl_utils
flutter pub global activate intl_utils
```

**Comment by denizmatsuri** [comment]
> flutter pub global deactivate intl_utils
> flutter pub global activate intl_utils

Thank you. It worked well 🫡
