### ISSUE TITLE
Load New string

### ISSUE THREAD

**Issue by hagag1919** [localizely/flutter-intl-vscode#112]
How to load new string from provider after the provider updated app language

**Comment by lzoran** [comment]
To better understand the problem you're facing, could you please share a reproducible example or code snippet that illustrates the problem? 

Also, maybe these examples might be of help: [example 1](https://github.com/localizely/flutter-intl-plugin-sample-app), [example 2](https://github.com/localizely/flutter-gen-l10n-example).
