### ISSUE TITLE
Extensions pollutes VS Code warnings with "The message with key KEY does not have metadata defined."

### ISSUE THREAD

**Issue by ospaarmann** [localizely/flutter-intl-vscode#117]
After setting up the extension, my "Problems" pane in VS Code is full of warnings, one for each key and translation file. Since I don't plan to add metadata for every key, this is quite annoying. Is there a way to disable the warning?

<img width="683" alt="Screenshot 2024-06-13 at 20 10 28" src="https://github.com/localizely/flutter-intl-vscode/assets/308086/93eed172-98e2-4f00-9edc-8303ad718057">

Sorry for the title spam, I hit ENTER by mistake and cannot delete the issue 🫠

**Comment by charlescyt** [comment]
Do you have another extension `ARB Editor` installed?
I believe those warnings are from `ARB Editor` instead.

**Comment by ospaarmann** [comment]
They indeed are. Thank you
