### ISSUE TITLE
Add support for a dot in the key

### ISSUE THREAD

**Issue by yoavrofe** [localizely/flutter-intl-vscode#15]
Support the common convention of adding a dot inside a key to create hierarchical IDs.

**Comment by aleksakrstic** [comment]
Hi @yoavrofe 
Unfortunately this will diverge from official practices for Flutter internationalization.
If official `intl` and `intl_translation` libraries start supporting that, we would gladly support it with the plugin as well.

Maybe you can use combination of camelCase and underscores for the hierarchy?
For instance: `page_home_welcomeTitle`.

**Comment by om-ha** [comment]
Hey @goranluledzija 

As you mentioned in the issue https://github.com/localizely/intl_utils/issues/85#issuecomment-1179223800

Can you please elaborate on:

> Maybe, it would be better to have separate action or script that would update such string keys than converting them automatically during generation.
