### ISSUE TITLE
Add a run command to support editing ARBs outside VSCode

### ISSUE THREAD

**Issue by yoavrofe** [localizely/flutter-intl-vscode#16]
When editing the arb files outside VSCode the plugin does not run until it's saved again inside VSCode. Add a run command or run automatically when the file is modified.

**Comment by aleksakrstic** [comment]
Hi @yoavrofe 
CLI tool already exists: https://pub.dev/packages/intl_utils
It reads the same configuration from `pubspec.yaml` file as plugins do.

Plugin documentation will be updated to link to this CLI tool with the upcoming plugin releases.

Hope this solves the issue.
