### ISSUE TITLE
Order of generated supportedLocales

### ISSUE THREAD

**Issue by davidmartos96** [localizely/flutter-intl-vscode#17]
When localizing for "en" and "es" (Spanish) the generated `supportedLocales` places "es" as first, so when the device has a different language, let's say German, Flutter will fallback to the first element in the list https://api.flutter.dev/flutter/material/MaterialApp/supportedLocales.html 
I think the correct behavior would be to use the "main_locale" setting from the plugin, so that in this case the default language for German would be English.

**Comment by aleksakrstic** [comment]
Hi @davidmartos96 
Added for the upcoming plugin update.

Thanks for reporting!

**Comment by davidmartos96** [comment]
Awesome! Thank you for the plugin, it works really smoothly!

**Comment by aleksakrstic** [comment]
@davidmartos96 
This is now fixed with plugin version `1.4.1`.

**Comment by davidmartos96** [comment]
Great, thanks!
