### ISSUE TITLE
Current locale was removed. Can we have it back?

### ISSUE THREAD

**Issue by orestesgaolin** [localizely/flutter-intl-vscode#18]
There was property S.of(context).localeName that's gone now. Can we have it back e.g. on a S.delegate?

**Comment by aleksakrstic** [comment]
Hi @orestesgaolin 
It was a left over attribute from the old version of the plugin, and was not representing currently selected locale, for a long time now.
For accessing current locale you should use `Intl.getCurrentLocale()` (https://api.flutter.dev/flutter/intl/Intl/getCurrentLocale.html).

Did you maybe use `S.of(context).localeName` for something else?

**Comment by orestesgaolin** [comment]
Hi, thanks for clarifying. If I can use Intl for that then that's great!
