### ISSUE TITLE
Can't change "S" class name 

### ISSUE THREAD

**Issue by bogdanmarinescu** [localizely/flutter-intl-vscode#2]
Extension generates an S class
`class S {
  S(this.localeName);`

this name should be defined by user

**Comment by goranluledzija** [comment]
Makes sense.
Going to make it configurable through `flutter_intl` configuration inside `pubspec.yaml` file in the project.

It was named `S` (abbreviated from "Strings") because it is short enough to be used inside the code repeatedly... 
Btw, how would you name it in your case?

**Comment by bogdanmarinescu** [comment]
> It was named `S` (abbreviated from "Strings") because it is short enough to be used inside the code repeatedly...
> Btw, how would you name it in your case?

I would probably name it "Localizations"

**Comment by chen-yumin** [comment]
Same feature request. I'd name it `I18n` myself.

**Comment by goranluledzija** [comment]
Thanks for the feedback.

This is now supported with v1.2.0 that is just published.

The configuration goes inside `pubspec.yaml`:
```
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
```

@bogdanmarinescu Class `Localizations` is already reserved by Flutter.
You can try with `AppLocalizations` or `I18n` as @chen-yumin proposed.
