### ISSUE TITLE
Placeholder typing

### ISSUE THREAD

**Issue by davidmartos96** [localizely/flutter-intl-vscode#20]
I was wondering if there is any way for the plugin to generate methods with `String` instead of `Object` as arguments.

```json
"hello_user": "Hello {name}",
"@hello_user": {
    "type": "text",
    "placeholders": {
        "name": {}
    }
},
```
Which generates:
```dart
String hello_user(Object name)
```

Maybe the type `String` could be inferred if the placeholder is defined with the `example` property. [Reference](https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#predefined-resource-attributes)
```json
"placeholders": {
    "name": {
        "example":  "Jake"
    }
}
```
Same strategy could be applied for the types `int` or `double`, although I haven't encountered that in my usecase.

**Comment by aleksakrstic** [comment]
Hi @davidmartos96 

Not sure if type inference from `example` field would be a good practice, it wouldn't cover properly all potential cases developers would use.
Is there any other motivation for this from your side, besides relying on strict types when passing arguments to key getters?

**Comment by davidmartos96** [comment]
@aleksakrstic The only motivation is to try to rely on strict typing really. I was just wondering if there is any way to do it.
Feel free to close the issue if you think is not a viable thing to do.

**Comment by aleksakrstic** [comment]
Hi @davidmartos96 
Will close it for now.
If some opportunity in the future allows better implementation, we will consider applying such strict types for arguments.
Thanks anyway for giving a feedback!
