### ISSUE TITLE
Inconsistencies when generating messages_all.dart

### ISSUE THREAD

**Issue by davidmartos96** [localizely/flutter-intl-vscode#21]
Every once in a while the plugin generates languages in a different order so I sometimes encounter this change on my git.
![image](https://user-images.githubusercontent.com/22084723/79045520-db108980-7c0b-11ea-9e2f-7faca7c79745.png)

It would be great if the code generator would be more consistent, for example using the locales in alphabetical order.

**Comment by goranluledzija** [comment]
Hi @davidmartos96 
I assume this was happening among team members that were using different Operating Systems...

With the newly released extension version `1.4.2` it should be fixed.
Compatible Android Studio plugin will be approved in a day or two.

**Comment by davidmartos96** [comment]
@goranluledzija Yes, it happened between Linux and macOS. Thanks for the quick update!

**Comment by js2702** [comment]
I'm having a similar issue but with the file l10n.dart with the getter `supportedLocales`. My team is using macOS and Linux, and it returns different results with version 1.4.2.

**Comment by goranluledzija** [comment]
Hi @js2702 
Thanks for spotting this!
It will be fixed with the next update.

**Comment by aleksakrstic** [comment]
@davidmartos96 @js2702 @kassim
This should be fixed with new IDE plugin version `1.5.0` and `intl_utils` version `1.3.0`.
