### ISSUE TITLE
Add web support

### ISSUE THREAD

**Issue by ach4m0** [localizely/flutter-intl-vscode#22]
Actually I'm working on a project with Flutter for web and I need to change manually file i10n.dart generated to add web support.

I think that you can add some option in pubspec.yaml like:

```yaml
flutter_intl:
  enabled: false
  enable_web: true
```

And then create the i10n file with support for browser:

```dart
[...]
import 'package:flutter/foundation.dart';
import 'package:intl/intl_browser.dart';
[...]
static Future<S> load(Locale locale) async {
  [...]
  final String localeName = kIsWeb ? (await findSystemLocale()) : Intl.canonicalizedLocale(name);
  [...]
}
```

Thanks!

**Comment by aleksakrstic** [comment]
Hi @ach4m0 

Did you try with following setup in Flutter for Web apps, in order to not manually edit generated `l10n.dart` file:

- call `findSystemLocale()` very early in you dart code, ie call `runApp(...)` after `findSystemLocale()` is completed
- implement `localeListResolutionCallback` by giving preference to system's locale

Note: I noticed that Flutter for Web does not pass browser's locales list to `localeListResolutionCallback`. Open issue: https://github.com/flutter/flutter/issues/40082
But browser's locale is available through:

- `findSystemLocale() ` future
- `Intl.systemLocale`

Will this work in your case?

**Comment by slavap** [comment]
@aleksakrstic 
No, it doesn't work. After: var s = await findSystemLocale() I'm getting the right locale code, but localization is not working, even manual S.load(Locale(s)) does not help.

**Comment by tsinis** [comment]
> @aleksakrstic
> No, it doesn't work. After: var s = await findSystemLocale() I'm getting the right locale code, but localization is not working, even manual S.load(Locale(s)) does not help.

Hmm interesting... workaround from @aleksakrstic is working good for me:
I'm grabbing locale just before runApp and passing it to a constructor of MyApp widget. Then you can do whatever you want with it... even load manually with S.load. on initState. Here is some very dirty example:

```
void main() async {
  await findSystemLocale().then((_detectedLocale) =>
      runApp(MyApp(_detectedLocale.substring(0, 2))));
}

class MyApp extends StatelessWidget {
  MyApp(this._detectedLocale);

  final String _detectedLocale;

...

  @override
  initState() {
    super.initState();
    S.load(Locale(_detectedLocale ?? 'en')).whenComplete(() => setState((){}));
    }
  }

...
```

I'm on latest Flutter master branch with latest VS Code Insders (if it does matter).

**Comment by slavap** [comment]
@tsinis initState() of what? In your code MyApp is declared as StatelessWidget

**Comment by tsinis** [comment]
> @tsinis initState() of what? In your code MyApp is declared as StatelessWidget 

Hey! As you can see there is ellipsis in this abstract code, so there can be anything above or bellow. For example StatefulWidget... or anything else you wish. It’s up on you how you will handle this string value. It’s workaround, so please don’t expect code aesthetics :)

**Comment by slavap** [comment]
@tsinis I'm just trying to find out the solution, sorry. setState() re-renders something, let's say the whole App, the question is - how it is different from calling S.load() before runApp() ?

**Comment by slavap** [comment]
@tsinis @aleksakrstic 
I'm out of ideas :-( Even on the latest dev 1.18.0-8.0.pre it just doesn't work, or I missing something obvious :-(
setState() doesn't help (on stateful App).
S.load() before runApp() doesn't help as well.

**Comment by tsinis** [comment]
> 
> S.load() before runApp() doesn't help as well.
> 

Hey @slavap!

I suppose, it's missing context... Anyways I've implemented very primitive language detection in default Flutter counter app (as I described earlier), so it's working on web as it have to. You can see it working in video:
https://youtu.be/NscybcV7E3k?t=230
or just clone & run it yourself:
https://github.com/tsinis/web_locale

Hope it helps!

**Comment by slavap** [comment]
@tsinis Thank you! Your test project works for me. The funny thing - I did practically the same in my project, and it is not working for some reason. Will try to find out what's wrong with it. At least I know it is working in simple app :-)

**Comment by slavap** [comment]
@tsinis @aleksakrstic Ok, I've ended up with the following solution, it works for both Android and Web, and also translates standard widgets (datepickers, ...)
```dart
import 'package:mypr/intl_utils_device.dart'
    if (dart.library.html) 'package:mypr/intl_utils_web.dart';

Future<void> main() async {
  var s = await systemLocale();
  print(s + "; " + Intl.systemLocale);
  //...
}
```
Then two files - one for devices, another one for web:
```dart
import 'package:intl/intl_standalone.dart';

Future<String> systemLocale() async {
  return findSystemLocale();
}
```
```dart
import 'package:intl/intl_browser.dart';

Future<String> systemLocale() async {
  return findSystemLocale();
}
```
And then the **main part** of it, setting locale of MaterialApp:
```dart
        MaterialApp(
          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: S.delegate.supportedLocales,
          locale: createLocale(Intl.systemLocale), // <<< this line makes it all working
```
```dart
import 'package:intl/locale.dart';
import 'dart:ui' as ui;

ui.Locale createLocale(String value) {
  var l = Locale.tryParse(value);
  if (l == null) return null;
  return ui.Locale(l.languageCode, l.countryCode);
}
```
So no need for manual calls of S.load() and setState().

**Comment by tsinis** [comment]
> @tsinis @aleksakrstic Ok, I've ended up with the following solution, it works for both Android and Web, and also translates standard widgets (datepickers, ...)
> 
> ```dart
> import 'package:mypr/intl_utils_device.dart'
>     if (dart.library.html) 'package:mypr/intl_utils_web.dart';
> 
> Future<void> main() async {
>   var s = await systemLocale();
>   print(s + "; " + Intl.systemLocale);
>   //...
> }
> ```
> 
> Then two files - one for devices, another one for web:
> 
> ```dart
> import 'package:intl/intl_standalone.dart';
> 
> Future<String> systemLocale() async {
>   return findSystemLocale();
> }
> ```
> 
> ```dart
> import 'package:intl/intl_browser.dart';
> 
> Future<String> systemLocale() async {
>   return findSystemLocale();
> }
> ```
> 
> And then the **main part** of it, setting locale of MaterialApp:
> 
> ```dart
>         MaterialApp(
>           localizationsDelegates: [
>             S.delegate,
>             GlobalMaterialLocalizations.delegate,
>             GlobalWidgetsLocalizations.delegate,
>             GlobalCupertinoLocalizations.delegate,
>           ],
>           supportedLocales: S.delegate.supportedLocales,
>           locale: createLocale(Intl.systemLocale), // <<< this line makes it all working
> ```
> 
> ```dart
> import 'package:intl/locale.dart';
> import 'dart:ui' as ui;
> 
> ui.Locale createLocale(String value) {
>   var l = Locale.tryParse(value);
>   if (l == null) return null;
>   return ui.Locale(l.languageCode, l.countryCode);
> }
> ```
> 
> So no need for manual calls of S.load() and setState().

Can confirm, your solution works great! Great job! Anyways I hope Flutter Team will fix https://github.com/flutter/flutter/issues/40082 soon, so it will all work as it have to without such workarounds. Do you mind to close this Issue?

P.S. i have slightly modified your code for my needs, so I can run use it with shared_preferences plugin with stored lang. code. If any one is interested, just let me know.

**Comment by slavap** [comment]
@tsinis Yes, this item can be closed, but I see no Close button, probably have no rights.
