### ISSUE TITLE
WARNING: key has an unsupported content type

### ISSUE THREAD

**Issue by talatkuyuk** [localizely/flutter-intl-vscode#23]
Flutter, Dart, I see in the output a warning:
`INFO: Generating localization files for the 'family_infopool' project...
WARNING: The 'familyCRSViewListTileYouAreMembersip' key has an unsupported content type.`

I couldn't figure out what causes this warning.

in intl_en.arb file, I use this:
`"familyCRSViewListTileYouAreMembersip": "{membershiptype, select, member {You are Member} moderator {You are Moderator} archived {You are Archived} other {membershiptype}}",`

in generated messages_en.dart file, I see:
`static m2(membershiptype) => "${Intl.select(membershiptype, {'member': 'You are Member', 'moderator': 'You are Moderator', 'archived': 'You are Archived', 'other': 'membershiptype', })}";`

in generated l10n.dart file, I see:
`String familyCRSViewListTileYouAreMembersip(Object membershiptype) {
    return Intl.message(
      '{membershiptype, select, member {You are Member} moderator {You are Moderator} archived {You are Archived} other {membershiptype}}',
      name: 'familyCRSViewListTileYouAreMembersip',
      desc: '',
      args: [membershiptype],
    );
  }`

in respective dart file,  I use:
`Text(S.of(context).familyCRSViewListTileYouAreMembersip(liveMembership.mtype))`
liveMembership.mtype is a String variable.

**Comment by aleksakrstic** [comment]
Hi @talatkuyuk 
Custom selects are not supported at the moment, but we plan to support it soon in one of upcoming plugin updates.

**Comment by talatkuyuk** [comment]
Thanks for quick reply.

Actually in https://github.com/dart-lang/intl/ there is Intl.select() custom constructor. 

It would be nice if localizely/flutter-intl-vscode can generate a dart file contains this issue in respective with Custom Selects.

I am going to wait the plugin update that you mentioned.

Thanks.

**Comment by aleksakrstic** [comment]
@talatkuyuk 
Custom selects are now supported with new plugin version `1.5.0`
