### ISSUE TITLE
Get localized text by String passed in at runtime

### ISSUE THREAD

**Issue by shawnlauzon** [localizely/flutter-intl-vscode#24]
Thanks for this plugin, which seems to be very easy to use. Unfortunately it's missing a key bit of functionality for my purposes.

Currently when I want to get a translated text, I access the getter like this:
`S.of(context).aMessageKey`

However in my case, the message keys are coming from a separate file and parsed at runtime, so I don't have a getter name at compile time. I would like to see an option something like this:
`S.of(context).text('aMessageKey')`

whose output would be exactly the same as the first.

**Comment by aleksakrstic** [comment]
Hi @shawnlauzon 
I guess you would like to use "ICU select" for such cases?

It is supported with plugin version `1.5.0`: https://github.com/localizely/flutter-intl-vscode/issues/12

**Comment by shawnlauzon** [comment]
Thanks @aleksakrstic for the quick response. Thanks for pointing out that feature, but I'm not sure it will work because of the number of keys. In your example 

```"pageHomeWelcomeRole": "{role, select, admin {Hi admin!} manager {Hi manager!} other {Hi visitor!}}"```

you have only 3 roles. In my case, it would be like there are 100 different roles, and so all of them would need to be inside the same message key, and from what I can tell they all need to be on the same line.

In any case, I think I've decided to go another route in my app which is to generate code rather than parse at runtime (I'm given a YAML file with much of the text of the app, and rather than parse the text at runtime, I will generate some classes at build time).

**Comment by aleksakrstic** [comment]
Hi @shawnlauzon 
Yes, if you have 100 different roles/options, "ICU select" would get complicated and wouldn't be a good way to go.

Unfortunately introducing dynamic keys would diverge from official Flutter internationalization and would loose the benefits from current autocomplete for key getters.
Thanks for sharing your case.

Good that you already have found an alternative solution.
