### ISSUE TITLE
Add explicit types to the generated code

### ISSUE THREAD

**Issue by ResoDev** [localizely/flutter-intl-vscode#25]
I absolutely LOVE this extension/CLI tool but it doesn't play well with more strict analysis rules.

When I disable `implicit-casts` inside `analysis_options.yaml`:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```
The following generated code inside `messages-*.dart` produces an `invalid_assignment` error:
```dart
class MessageLookup extends MessageLookupByLibrary {
  String get localeName => 'en_US';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages(_) => <String, Function> {
    "SignIn_Button" : MessageLookupByLibrary.simpleMessage("Sign In"),
  };
}
```

The `_notInlinedMessages` method should be types as follows.
```dart
class MessageLookup extends MessageLookupByLibrary {
  String get localeName => 'en_US';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static Map<String, Function> _notInlinedMessages(_) => {
    "SignIn_Button" : MessageLookupByLibrary.simpleMessage("Sign In"),
  };
}
```

Additionally, it wouldn't hurt if you added another `ignore_for_file` comment for `type_annotate_public_apis` 😉

**Comment by aleksakrstic** [comment]
Hi @ResoDev 
Thanks for clear example!
I agree with you.

However, those `messages_*.dart` files are generated by `intl_translation` library on which the plugin relies under the hood for some parts. Hence we don't have direct impact on that generated file.

There are already reported similar issues there, like: https://github.com/dart-lang/i18n/issues/556

**Comment by ResoDev** [comment]
Thank you for the response, let's hope that it will be fixed on their side quickly.
