### ISSUE TITLE
The generated code doesn't pass linter checks

### ISSUE THREAD

**Issue by agordeev** [localizely/flutter-intl-vscode#27]
I use `pedantic` package, and the generated code doesn't pass checks:

<img width="595" alt="Screenshot 2020-05-06 at 16 15 59" src="https://user-images.githubusercontent.com/2883524/81181361-068d5680-8fb5-11ea-95c4-386c8dc8d73d.png">

It'd be great to make the plugin open source so we can fix these easy stuff ourselves.

**Comment by aleksakrstic** [comment]
Hi @agordeev 
Thanks for the feedback.

Newly released extension version `1.8.0` has removed mentioned `pedantic` issues for `l10n.dart` file.

However, `messages*.dart` files are generated by https://github.com/dart-lang/intl_translation package on which the extension relies on.
