### ISSUE TITLE
Plugin not generating on VS Code

### ISSUE THREAD

**Issue by miguelpruivo** [localizely/flutter-intl-vscode#28]
It looks like something is broken. I can't get any proper files to be generated lately (I'm on 1.8.0) and even if I delete generated folder completely, it just creates incomplete files exactly like in the screenshot.

Neither it creates the PT files, nor the default ones (messages_all).

<img width="285" alt="Captura de ecrã 2020-05-15, às 02 10 42" src="https://user-images.githubusercontent.com/27860743/82001333-de57c480-9652-11ea-8b3c-70d6782e7ac0.png">

Edit: I was able to make it create automatically the `messages_all` file and even the `pt` but the generated strings are completely blank.
```
final messages = new MessageLookup();

typedef String MessageIfAbsent(String messageStr, List<dynamic> args);

class MessageLookup extends MessageLookupByLibrary {
  String get localeName => 'pt';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages(_) => <String, Function> {

  };
}
```

There isn't a single one there. The `.arb` in the other end, is complete as it should. What can I do to make it generate?

Thanks.

**Comment by miguelpruivo** [comment]
Wrong package. Sorry.

**Comment by aleksakrstic** [comment]
Hi @miguelpruivo 
Could you check if you have the same keys in `intl_pt.arb` as you have in your main ARB file (assuming your `intl_en.arb` is the main locale as it is a default config)?

Extension looks for keys from main ARB files and tries to find them in other ARB files

**Comment by miguelpruivo** [comment]
@aleksakrstic I believe they have the same exact keys, I even used a diff on both files to check for differences but there’s nothing that I can make it to trigger a generate.

If I could only see a console error of what might be causing it, that would help a lot.

Any idea?

**Comment by aleksakrstic** [comment]
@miguelpruivo You can see what extension logs into `Output` view in VS Code, when you choose `Flutter Intl` in the drop-down selection.

If you find something there, just share it here for other users if they come across the same issue.

**Comment by miguelpruivo** [comment]
@aleksakrstic I can't see anything other that just the normal Output (which doesn't actually show any errors).

Just to make sure, I've scripted on the Dartpad to check for equality in both arb files to see if both have exactly the same keys, and turns out they do.

I've a release scheduled for today and I don't know what else to do other than replacing the plugin for something else to generate the translations. 😞

**Comment by aleksakrstic** [comment]
@miguelpruivo  If you haven't already tried, you can clone `intl_en.arb` file and rename it to `intl_pt.arb`, and see if that fixes the issue.
If that generates expected code in `messages_pt.dart` then you can compare and see where it breaks.

Maybe you can also check if your `intl_pt.arb` file is a valid json file?
For instance, check if there is excessive comma (",") after the last key-value pair in that file.

If CLI tool `intl_utils` returns error code 2, there is definitely some error.

If that doesn't help, you can share your file here, or send it to me directly if it is confidential.

**Comment by miguelpruivo** [comment]
@aleksakrstic fixed. Just found it. Our copyrighter had the arguments `{ }` translated as well, that was the issue.

Thank you for your time!

**Comment by aleksakrstic** [comment]
@miguelpruivo Glad that you found the solution.
Thank you for reporting this.

Seems there is definitely room for improving error logging for the extension.
Hence I created additional issue for that https://github.com/localizely/flutter-intl-vscode/issues/30
