### ISSUE TITLE
How to extract a string from my code to .arb file

### ISSUE THREAD

**Issue by bigbang489** [localizely/flutter-intl-vscode#32]
In your document: "Extract string to ARB files using code actions. The dialog will ask you to enter the string key, which will be extracted to ARB files together with the selected content."

But I couldn't find the option in Source Actions... or Refactor...

**Comment by aleksakrstic** [comment]
Hi @bigbang489 
Here is animated video that explains it better: https://twitter.com/localizely/status/1255175275454881793
However, thanks for the feedback, maybe we should put such animation in documentation page for the IDE extension.

**Comment by corymalcolmtaylor** [comment]
Is there a way to do that in vscode?  The option does not appear for me in vscode (latest version).

**Comment by lzoran** [comment]
Hi @corymalcolmtaylor,

I've just tested it on my machine, and it works well 😕.
Could you give us an example of what you are trying to extract?

Note, you need to select the whole string that you want to extract together with the quotes and then to trigger the "Extract to ARB" code action via lightbulb or `Ctrl+.`?

**Comment by corymalcolmtaylor** [comment]
Thanks that worked, I was not selecting the whole string and quotes, I was just putting the cursor in the string.

**Comment by lzoran** [comment]
Glad it works @corymalcolmtaylor!

It seems that there is a space for improvement.
We will try to make this action more intuitive in the future.

**Comment by apremalal** [comment]
It doesn't appear in my vscode. I tried copying the whole string with quotes and it didn't work.

**Comment by lzoran** [comment]
Hi @apremalal,

I've tried to reproduce your issue on the `VS Code 1.72.2`, with `Flutter 3.3.5`, and `Flutter Intl 1.18.2`, but everything seems to work as expected.  

![vsc-flutter-intl-extract-to-arb](https://user-images.githubusercontent.com/15170421/196909490-1f63ad1c-690f-4aca-9382-2d57813a68e3.gif)

Not sure what might be the issue. 😕 

Do you have enabled Flutter Intl extension for the project (`Ctrl+Shift+P` > `Flutter Intl: Initialize`)?

**Comment by ayoubboumzebra** [comment]
I am using VSCode and this trick works:
`Ctrl+Shift+P > Flutter Intl: Initialize`
