### ISSUE TITLE
Potential license infringement

### ISSUE THREAD

**Issue by orestesgaolin** [localizely/flutter-intl-vscode#33]
Hey, I enjoy using and learning from Flutter Intl and other related tools and libraries and I wanted to let you know that probably there is a license infringement happening with regards to [intl_translation](https://pub.dev/packages/intl_translation) package. 

In particular the `parser.dart` file of the [intl_utils 1.6.0](https://pub.dev/packages/intl_utils) is using code from the `icu_parser.dart` from current version of [intl_translation](https://github.com/dart-lang/intl_translation/blob/master/lib/src/icu_parser.dart). There are slight differences between them, but I think it would be in good taste to keep the original copyright notice and also provide relevant NOTICE file along with the source code.

I'm not expert in licensing so perhaps I'm wrong in this case, but just wanted to let you know that such potential infringement took place.

Peace ✌️

**Comment by aleksakrstic** [comment]
Hi @orestesgaolin 
Thanks for spotting this. Even if the file differs a bit, it makes sense to do that.
It will be updated with the upcoming release.

**Comment by aleksakrstic** [comment]
It is updated with new version `1.6.1` of `intl_utils`
