### ISSUE TITLE
intl_utils 1.6.1 depends on petitparser >=1.1.3 <3.0.0

### ISSUE THREAD

**Issue by slavap** [localizely/flutter-intl-vscode#34]
Please upgrade to petitparser 3+, because I have dependencies conflict with other packages.

**Comment by aleksakrstic** [comment]
Hi @slavap 
Seems that would conflict with `flutter_test`.
There is an open issue for `intl_translation` library https://github.com/dart-lang/i18n/issues/557 and will affect `intl_utils` as well.
We need to wait till it goes into stable channel.

By the way, now there is a separate git repo for `intl_utils` where issues related to Dart lib can be reported: https://github.com/localizely/intl_utils

**Comment by slavap** [comment]
@aleksakrstic then there should be separate version for beta, dev, and master channels, many developers are not on stable channel.

**Comment by aleksakrstic** [comment]
Moving the issue to https://github.com/localizely/intl_utils/issues/1
