### ISSUE TITLE
Updated to Flutter 1.20 and I10n.dart does not get regenerated (VSCode)

### ISSUE THREAD

**Issue by olivierbrand** [localizely/flutter-intl-vscode#39]
Just updated Flutter, whenever I change an existing arb file, the generated class does not change anymore

**Comment by aleksakrstic** [comment]
Hi @olivierbrand 
I just tried it with Flutter v1.20.2 and it works.

Did you check the `Output` view in VS Code for `Flutter Intl` if it prints some message for invalid ARB file or similar?

**Comment by olivierbrand** [comment]
Ahh, that was it, a comma was missing somewhere. I had 2 arb files, the second one did not have the issue but nothing was getting generated, was confused... All good! Thanks for the great plugin
