### ISSUE TITLE
Add compatible plugin for Android Studio

### ISSUE THREAD

**Issue by marcruse** [localizely/flutter-intl-vscode#4]
We like this plugin very much!
It would be good if some of our team members that use Android Studio IDE, could use it as well.

**Comment by bogdanmarinescu** [comment]
Or maybe a simple cli app that we can call any time we want. It can be either a [build_runner](https://pub.dev/packages/build_runner) command or a node app.

**Comment by goranluledzija** [comment]
A plugin for Android Studio was already in the plan.
CLI tool as well.
We are working on this.

**Comment by goranluledzija** [comment]
@marcruse @bogdanmarinescu 
Plugin for IntelliJ / Android Studio is published: https://plugins.jetbrains.com/plugin/13666-flutter-intl
CLI tool (Dart package) is available as well: https://pub.dev/packages/intl_utils

All three (VS Code, IntelliJ/Android Studio & Dart package) read the same configuration from `pubspec.yaml` file, so they are fully compatible.

Would like to hear your feedback on how it fits your needs.

**Comment by marcruse** [comment]
Just tried, works great!
