### ISSUE TITLE
Flutter Intl extension for VS Code not working in new vscode

### ISSUE THREAD

**Issue by tazik561** [localizely/flutter-intl-vscode#40]
I updated my vscode to :

```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-6-amd64
```
I am using Flutter Intl extension(v1.10.0) for VS Code for Localizely platform. But after updating vscode, seems Flutter Intl not work and it is not generate my text after save my text inside intl_en.arb??

**Comment by aleksakrstic** [comment]
Hi @tazik561 
I just tried it with the latest VSCode version. Works as expected.
Could you check if there is something in "Output" view in your VSCode, for "Flutter Intl"?
Could be your arb file is not a well formed

**Comment by tazik561** [comment]
yes, vscode did not error when arb file was not a well formed.I fixed arb file  formed and  Works as expected.
