### ISSUE TITLE
Keys auto generation not working anymore

### ISSUE THREAD

**Issue by vadrian89** [localizely/flutter-intl-vscode#43]
Hello,
For some time now, I can't seem to make key generation on save work.
I have to restart VS Code to have the keys available.

This is the environment:

Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap

Any ideeas?

**Comment by lzoran** [comment]
Hi @vadrian89,

Thanks for reporting this issue!

Unfortunately, I wasn't able to reproduce it.
Could you check the "Output" view for "Flutter Intl" in your VS Code IDE, maybe there is something useful?
Also, could you check if your ARB files are well-formed?

**Comment by vadrian89** [comment]
Hi @lzoran, thanks for answering!

From what I noticed, it was because I had another Flutter project with Intl. I removed the other project from VS Code workspace and now it generates the keys on save.

Is this the intended behaviour?

**Comment by lzoran** [comment]
Hi @vadrian89,

Interesting, workspaces with multiple projects are supported. 🤔 

I've tried to reproduce this issue again with two flutter projects opened within the same workspace, but without success.

Currently, the Flutter Intl extension detects when an ARB file is saved and tries to find a project for that file. If found project has enabled Flutter Intl extension (`flutter_intl` config within `pubspec.yaml` file), then a generation of localization files is triggered.

**Comment by vadrian89** [comment]
Interestingly enough it's working for multiple projects now, maybe something went wrong when I configured the project to work with Intl...
Sorry for the trouble, it bugged me for a week now, but after I removed the other project it suddenly works.
You can close the issue.
