### ISSUE TITLE
Code action (Ctrl+.) for adding string to arb file

### ISSUE THREAD

**Issue by bambinoua** [localizely/flutter-intl-vscode#45]
There is a text on plugin's page

> Extract string to ARB files using code actions. The dialog will ask you to enter the string key, which will be extracted to ARB files together with the selected content.

Dut there is no such code action in VS code. Is it bug of VS Code or plugin?

**Comment by lzoran** [comment]
Hi @bambinoua,

First of all, thank you for raising an issue and helping us to improve the Flutter Intl extension.
Maybe we should be more descriptive regarding this code action.

Have you tried to select the whole string that you want to extract together with the quotes and then to trigger "Extract to ARB" code action via lightbulb or  `Ctrl+.`?

**Comment by bambinoua** [comment]
@lzoran thank you very much! I think this should be described on plugin's oage.

**Comment by ascott18** [comment]
This is very confusing. Why is it not sufficient to just have your cursor _within_ the string that you want to extract? Why is selecting the whole string required?
