### ISSUE TITLE
Localizely generates the files even for projects i have never initialized

### ISSUE THREAD

**Issue by HerrNiklasRaab** [localizely/flutter-intl-vscode#47]
The plugin generates me the files even for a project I have never initialized. How can I disable this? Is this a bug? Is this related to workspaces?

![image](https://user-images.githubusercontent.com/28401593/96025460-7271c600-0e55-11eb-832f-6a26ecd75c43.png)

Two different repos
![image](https://user-images.githubusercontent.com/28401593/96025575-99c89300-0e55-11eb-9933-d3b054e06edd.png)

**Comment by aleksakrstic** [comment]
Hi @HerrNiklasRaab 
Thanks for spotting this. The fix is released with extension version `1.12.1`.
Now it should generate the files only for initialized projects.

**Comment by HerrNiklasRaab** [comment]
Thanks, can confirm the fix!
