### ISSUE TITLE
Pause the generation

### ISSUE THREAD

**Issue by abianche** [localizely/flutter-intl-vscode#49]
Hi,

is there a way to pause the extension. I could of course temporarily remove it from vscode, but that's not very handy.
My use case is that while doing some merging, I don't want the code to be generated automatically, which leads me to having some code conflicts.

**Comment by aleksakrstic** [comment]
Hi @abianche 
You can temporarily disable the extension by setting `enable: false` flag in `pubspec.yaml` file:

    flutter_intl:
      enabled: false
