### ISSUE TITLE
S load function should be SynchronousFuture

### ISSUE THREAD

**Issue by isacjunior** [localizely/flutter-intl-vscode#5]
According to the documentation:
Its load method returns a SynchronousFuture because no asynchronous loading needs to take place.

Without this, occur errors in Widgets when use `S` class in Widget tests.

```dart
SynchronousFuture<DemoLocalizations>(DemoLocalizations(locale));
```

More information: https://flutter.dev/docs/development/accessibility-and-localization/internationalization

**Comment by aleksakrstic** [comment]
Hi @isacjunior,
Given example with `SynchronousFuture` from the provided link is for alternative localization implementation, when hardcoded key-value map is used in the code and not loaded from ARB files with _Intl_ library.
Which is not suggested for production apps and its maintainance.

This plugin relies on _Intl_ library.

I added a simple test for widget to our sample app git repo: https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/test/localized_widget_test.dart

Does that example solve your problem how to write tests for Widgets in your case?
