### ISSUE TITLE
Feture request: ability to specify custom intl folders

### ISSUE THREAD

**Issue by nt4f04uNd** [localizely/flutter-intl-vscode#51]
I would like to change the folder where the localization files are preserved:
- Option for ARB
- Option for message definitions
- Option for the generated messages

**Comment by aleksakrstic** [comment]
This is implemented with version 1.13.0.

    flutter_intl:
        arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
        output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
