### ISSUE TITLE
null safety support

### ISSUE THREAD

**Issue by martin-robert-fink** [localizely/flutter-intl-vscode#54]
Is there a timeline to add null safety support?  The current plug-in has issues when Dart is set to >=2.12

**Comment by aleksakrstic** [comment]
Hi @martin-robert-fink 
Yes, the plan it to add nullsafety support of course.
We will see if it will be supported by the plugin's dependency soon, there is an open issue https://github.com/dart-lang/i18n/issues/563 that is a blocker.
I expect to be supported by the plugin before sound nullsafety goes into Dart's Stable channel .

**Comment by anamsantos** [comment]
Hi guys.
Some news about this issue?

**Comment by aleksakrstic** [comment]
The main discussion about null-safety support is here https://github.com/localizely/intl_utils/issues/14 since that is the core package under the hood.

Will use this issue for IDE plugin migration after `intl_utils` migration.

**Comment by aaqibism** [comment]
Seems like `intl_utils` was migrated to v2.0.0 which now supports null-safety. Any timeline on an update?

**Comment by aleksakrstic** [comment]
Hi everyone,
IDE plugin version `1.4.0` is now released.
Supports null-safety and uses `intl_utils 2.1.0` under the hood.
