### ISSUE TITLE
flutter-intl commands in command palette not working with several projects opened

### ISSUE THREAD

**Issue by FaisalMohammadi** [localizely/flutter-intl-vscode#55]
I am trying to remove or add a locale or initialize it from command Palette, but it does not work with several projects opened in vscode. Is it possible to tell or set flutter-intl-vscode to a specific project in a workspace

**Comment by aleksakrstic** [comment]
Hi @FaisalMohammadi 
In case you have multiple projects in your VS Code workspace, and you run a command from the Command Palette, then it should first ask you to what project you want to apply the command.

In case it does not work like that for you, could you share more info? 
Like reproduction steps, VS Code version, Flutter Intl extension version, and your workspace structure if possible?

**Comment by FaisalMohammadi** [comment]
i have vs code 1.51.1
flutter Intl 1.13.0 
flutter 1.22.0 and 2 projects opened in my workspace
it just happens nothing when i run the Flutter Intl command.

it is working fine with just one project opened, but not with several projects.

**Comment by aleksakrstic** [comment]
I just tried with downloaded projects https://github.com/localizely/flutter-intl-plugin-sample-app and https://github.com/localizely/flutter-ota-sample-app that I put into workspace.
Selected `Flutter Intl: Add locale` in Command Palette, and it offered me to choose the project:
<img width="652" alt="Screenshot 2020-11-25 at 01 15 44" src="https://user-images.githubusercontent.com/59895497/100166095-25edc180-2ebc-11eb-92e2-6405fb0b47e4.png">

After project selection it offered to type locale code I want to add.

Could you try it with the same projects I did? 
Just to eliminate some cases.

If that does not help, could you check if Flutter Intl extension printed something in its logs:
<img width="385" alt="Screenshot 2020-11-25 at 01 22 38" src="https://user-images.githubusercontent.com/59895497/100166350-d2c83e80-2ebc-11eb-9676-e25f6ebdf2fb.png">

**Comment by FaisalMohammadi** [comment]
flutter int does appear with one project but with more then one project i did not see it in output dropdown.

and i downloaded the same project and testet it happens nothing.

<img width="1373" alt="flutter intl" src="https://user-images.githubusercontent.com/61777855/100207492-efd62f00-2f07-11eb-85a2-52e6a074dacc.png">

**Comment by FaisalMohammadi** [comment]
![flutter intl](https://user-images.githubusercontent.com/61777855/100209318-02e9fe80-2f0a-11eb-9070-7330f0504264.gif)

**Comment by FaisalMohammadi** [comment]
![flutter intl](https://user-images.githubusercontent.com/61777855/100210147-f2865380-2f0a-11eb-9e85-30633d74ac78.gif)

**Comment by FaisalMohammadi** [comment]
![Uploading flutter intl (1).gif…]()

**Comment by FaisalMohammadi** [comment]
![flutter intl (1)](https://user-images.githubusercontent.com/61777855/100211666-b3590200-2f0c-11eb-96c2-2120aef0e8ef.gif)

**Comment by FaisalMohammadi** [comment]
@aleksakrstic i have just found where the problem was. It was in my workspace. I did not opened my projects in a workspace rather in a folder and i had also tried to put my projects in a workspace, but again i put every project in a folder inside a workspace.

i created a proper workspace and opened my projects inside and it worked.

thank you for investing your time to help me.
