### ISSUE TITLE
Change main locale ?

### ISSUE THREAD

**Issue by dleurs** [localizely/flutter-intl-vscode#57]
Hello,
Is there a way to change main locale please ? When I try to remove main, I got error "The main locale can't be deleted".
Thank you

**Comment by aleksakrstic** [comment]
Hi @dleurs 
Did you try with config parameter in `pubpec.yaml` from the extension [documentation](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl)?

    flutter_intl:
        ...
        main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en

**Comment by dleurs** [comment]
Thank you it worked
