### ISSUE TITLE
Does this support date formatting?

### ISSUE THREAD

**Issue by expresidx** [localizely/flutter-intl-vscode#61]
```
"publishedDate": "Published on {published, date, short}"
```

The result is always skipped,
```
// skipped getter for the 'publishedDate' key
```

I cannot find any example to do the right way or does this plugin doesn't support at all?

**Comment by lzoran** [comment]
Hi @expresidx,

Thanks for reporting this!
You are right, this kind of date formatting is not supported, so it will be skipped.
Have you found some [Intl](https://github.com/dart-lang/intl) documentation that suggesting this kind of date formatting?


Does a bit different approach work for you?

```
"publishedDate": "Published on {date}"
```

```
var formattedDate = DateFormat.yMd().format(DateTime.now()); // format your date
...
Text(S.of(context).publishedDate(formattedDate))
```

**Comment by expresidx** [comment]
Well I thought you should mention it on the front page. I was trying to figure out my self the whole day why my code isn't working.

**Comment by lzoran** [comment]
You are right.
It would be useful to have some documentation regarding the usage of formatted dates in messages.
We will add that in one of the upcoming extension releases.
