### ISSUE TITLE
Question: Is there a way to setup custom paths?

### ISSUE THREAD

**Issue by CassiusPacheco** [localizely/flutter-intl-vscode#62]
The documentation states:
> NOTE: The extension generates and maintains files inside lib/generated/ folder which you should not edit manually. But you should keep these files in your project repository.

I'd like to setup a custom path for the generated files, but I could not find a way of doing so. Is it possible?

Thanks

**Comment by aleksakrstic** [comment]
Hi @CassiusPacheco 
Have you try `arb_dir` & `output_dir` params explained on https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl under "Configuration options" section?
