### ISSUE TITLE
Doubling some variables in generated file

### ISSUE THREAD

**Issue by EliasDeuss** [localizely/flutter-intl-vscode#63]
<img width="320" alt="Screenshot_19" src="https://user-images.githubusercontent.com/13773566/107438909-2292cb00-6ae6-11eb-96ca-60e5b9349fc3.png">

This happens whenever it regenerates and I have to manually go in and remove them each time.

**Comment by lzoran** [comment]
Hi @EliasDeuss,

Thanks for reporting this!

I've tried to reproduce this issue, but without success. :(

Could you give us more details regarding this issue?
- Does this occur for all kind of messages or only for some?
- Could you give us an example of the original message from the ARB file?
- Do you also have a problem with duplicates within the `generated\l10n.dart` file?
- How do you trigger the generation of localization files (updating ARB files and leaving Flutter Intl extension generation or something else)?

The Flutter Intl extension uses the `intl_translation` package for generating the `messages_*.dart` files. 
There is an open similar [issue](https://github.com/dart-lang/i18n/issues/509) on the `intl_translation` repo, but I'm not sure if they are connected without more details.

**Comment by lzoran** [comment]
Hi @EliasDeuss,

I've succeeded to reproduce this issue.
Could you check that you may not have forgotten to update the metadata (`@@locale`, `_locale`) in the ARB files?

**Comment by EliasDeuss** [comment]
@lzoran yes it was that, another arb file had the same language tag.
