### ISSUE TITLE
Problem with placeholder in translation

### ISSUE THREAD

**Issue by Pistacchione** [localizely/flutter-intl-vscode#64]
Hi,

I have a strange behaviour with placeholder in translation string.
As in your example, if I put this string in `arb` file `"pageHomeWelcome": "Welcome {name}"`,

generated code in `l10n.dart` is:

``` 
/// `Welcome {name}`
String pageHomeWelcome(Object name) {
  return Intl.message(
    'Welcome $name',
    name: 'pageHomeWelcome',
    desc: '',
    args: [name],
  );
}
```

and generated code in `messages_en_US.dart` is:

```
static m1(name) => "Welcome ${name}";

static _notInlinedMessages(_) => <String, Function> {
  "pageHomeWelcome" : m1
};
```

then if I reference key in dart code this error occur:
<img width="874" alt="Schermata 2021-02-19 alle 14 15 45" src="https://user-images.githubusercontent.com/11761177/108509047-013b9700-72bd-11eb-9fda-728ba6dcbbbc.png">

Currenty Flutter version I use is `1.22.6`, VSCode Flutter Intl extension `1.13.0`

Thanks

**Comment by lzoran** [comment]
Hi @Pistacchione,

I believe that the problem is in `content` type mismatch.
Does wrapping translation with the `Text` widget solve the problem?
```
content: Text(S.of(context).pageHomeWelcome('Hello'),
```

**Comment by Pistacchione** [comment]
Hi @lzoran,

yes, wrapping translation with `Text` widget solve te problem!

Thank you very much for quick response!
