### ISSUE TITLE
No instance of L present in the widget tree

### ISSUE THREAD

**Issue by JonasHiltl** [localizely/flutter-intl-vscode#66]
I have followed the instructions to intialize and add the two languages de and en. I have the generated files for both languages but changed the `class_name` to L instead of S. I have also added the neccessary delegates and supported languages inside of my MaterialApp as seen below, but when I try to start the app I get the error that an instance of L isn't found in the widget tree.
```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.system,
      theme: ThemeData(
        colorScheme: colorScheme,
        primaryColor: colorScheme.primary,
        accentColor: colorScheme.secondary,
        backgroundColor: colorScheme.background,
      ),
      localizationsDelegates: [
        L.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: L.delegate.supportedLocales,
      home: Scaffold(
          body: Row(
        children: [LeftSide(), RightSide(), Text(L.of(context).hello)], //get error
      )),
    );
  }
}
```
I'm developing for a windows desktop app.

**Comment by aleksakrstic** [comment]
Hi @JonasHiltl 
Could you compare your app setup with this sample app: https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/lib/main.dart ?

Windows is supported as well, that shouldn't be the cause.

**Comment by JonasHiltl** [comment]
For some reson I couldn't access the L class in the body of the Scaffold as seen above but when using it in a different page it's all working.

**Comment by aleksakrstic** [comment]
I would say it should be approached the same way as when localizing the `title` of MaterialApp - by using [onGenerateTitle](https://api.flutter.dev/flutter/material/MaterialApp/onGenerateTitle.html) instead of `title` attribute
