### ISSUE TITLE
Add the option to disable/ignore one or more locales

### ISSUE THREAD

**Issue by bogdanmarinescu** [localizely/flutter-intl-vscode#7]
It will be nice to have a fast way to temporary ignore a locale until it's .arb it's fully translated.

Maybe something like this?
`
flutter_intl:

  enabled: true
 
 ignore_locales: 
    - "de_DE"
    - "fr_FR"
`

**Comment by goranluledzija** [comment]
Hi @bogdanmarinescu 
Could you give us more info, like in what cases it bothers you if the code is generated for incomplete locale?
You just do not offer that locale for the end-user in UI, right? Or you have a different app setup where it depends more on this extension?

We are trying to make plugin configuration as simple as possible, so trying to figure out the motivation for this.

**Comment by bogdanmarinescu** [comment]
> You just do not offer that locale for the end-user in UI, right? Or you have a different app setup where it depends more on this extension?

Let's say I have a partial localized  de.arb  in my project. If the user has the OS (Android in this case) set to German he/she will see that incomplete localization.

**Comment by goranluledzija** [comment]
Ok, I see.
Will add this to the roadmap, but probably with lower priority.

Thanks for reporting this case.

**Comment by bogdanmarinescu** [comment]
I can filter the locales in localeresolutioncallback, so I guess there is no need for this functionality. sorry for wasting your time.

**Comment by goranluledzija** [comment]
No problem, it is useful to hear what are the challenges devs face...

Will skip this enhancement, and leave it to devs to rely on `localeListResolutionCallback` and `localeResolutionCallback` for similar needs.
