### ISSUE TITLE
Placeholder not generated if string contains '<' sign

### ISSUE THREAD

**Issue by liri2006** [localizely/flutter-intl-vscode#71]
If string would be something like this - "Consider such expression: 0 < {value}", then no parameter would be generated, just a plain getter. Works for '>' though ;)

**Comment by lzoran** [comment]
Hi @liri2006,

This issue is fixed with the latest version of the Flutter Intl extension (`1.16.0`).

**Comment by liri2006** [comment]
@lzoran Thanks!
