### ISSUE TITLE
Can't build because of missing nullable types

### ISSUE THREAD

**Issue by miguelpruivo** [localizely/flutter-intl-vscode#72]
<img width="1173" alt="Captura de ecrã 2021-06-02, às 14 43 41" src="https://user-images.githubusercontent.com/27860743/120491206-f232ad80-c3b0-11eb-8439-fafab87e7073.png">

This is a major issue because I can't build and generated files always come up without nullable types support.

**Comment by lzoran** [comment]
Hi @miguelpruivo,

The Flutter Intl extension checks the min version of the `sdk` under the `pubspec.yaml` file and generates localization code according to that value.

Could you check if updating the min `sdk` value solves your problem?

```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

**Comment by miguelpruivo** [comment]
Hi @lzoran this is my environment:
```
environment:
  sdk: ">=2.13.0 <3.0.0"
```
It was working fine until today when intl updated and for some reason I start experiencing this issue.

**Comment by lzoran** [comment]
Interesting...

I've tried your environment config, and everything works fine on my machine. 😕 

The Flutter Intl extension relies on the globally activated `intl_utils` package. For Flutter projects that have min `sdk` constraint `>=2.12.0`, the extension should activate the `intl_utils ^2.0.0`.

Probably something went wrong after the update. 
Maybe deactivating the currently active `intl_utils` package and re-triggering the generation could help?

* `flutter pub global deactivate intl_utils`

* Update one of the arb files and save it (this should install the proper `intl_utils` version and trigger generation)

*  Check if generated code is fixed
   Check if proper `intl_utils` is activated (`flutter pub global list`)
   Check if there are some errors under the `Output > Flutter Intl` window

In case this does not help, could you please provide us more details so we can try to reproduce this issue (VS Code version, Flutter Intl extension version, Flutter version)?
