### ISSUE TITLE
Emacs extension

### ISSUE THREAD

**Issue by NANASHI0X74** [localizely/flutter-intl-vscode#75]
I was surprised to see that these repositories linked from the extension marketplace sites are actually empty apart from a short readme and license. Can we take a look at the source code?
With that maybe it would be possible to port the extension to make an emacs version

**Comment by aleksakrstic** [comment]
Hi @NANASHI0X74 
So you develop Flutter apps using Emacs and want to port this extension to Emacs?

**Comment by NANASHI0X74** [comment]
possibly, but I was primarily just bewildered that the repository link is empty. So what about the code for the actual editor extension? Is the source code public? What's the license on that code?

**Comment by aleksakrstic** [comment]
IDE plugin is not open-source for now, as stated in the README file.
Its core, is open-source https://pub.dev/packages/intl_utils

**Comment by NANASHI0X74** [comment]
🙈 well, I guess I should have read that properly. I just kinda scanned it and figured it's just a short description and link to the marketplace.
Is it necessary to have both the repository and issue tracker links on the extension page at the same time? If there's no code here and the repository is just used as an issue tracker, it seems pointless to have this "repository" link at all.
Additionally confusing is that the repo contains an MIT license. What does that apply to? The README? :D

**Comment by aleksakrstic** [comment]
Yes, the license applies to repository where it is located, not much relevant in this case.
