### ISSUE TITLE
Command  for generating dart files

### ISSUE THREAD

**Issue by lgLindstrom** [localizely/flutter-intl-vscode#8]
Would be nice to have 
Flutter Intl: generate

**Comment by goranluledzija** [comment]
Hi @lgLindstrom 
"generate" command is usually automatically triggered whenever a change in relevant files (ARB, pubspec.yaml) is saved.

In what cases you noticed there is a need to manually trigger that command?

**Comment by lgLindstrom** [comment]
My mistake,, sorry.
I did not understand how it should be working.

Den sön 9 feb. 2020 01:48Goran Luledzija <notifications@github.com> skrev:

**Comment by goranluledzija** [comment]
No problem,
it is probably a sign we need to update the documentation.
