### ISSUE TITLE
Can't add an int as a key for Custom selects

### ISSUE THREAD

**Issue by db-dblank** [localizely/flutter-intl-vscode#81]
I'm trying to add this to my ARB file:

```json
"weekOfMonthType": "{weekOfMonth, select, 1{First} 2{Second} 3{Third} 4{Fourth} other{Last}}",
```

But getting this error:

```
INFO: Generating localization files for the 'flutter_app' project...
ERROR: The 'weekOfMonthType' key will be ignored due to parsing errors.
exit code 0
```

Expected outcome would be:

```dart
static String m0(weekOfMonth) => "${Intl.select(weekOfMonth, {
            '1': 'First',
            '2': 'Second',
            '3': 'Third',
            '4': 'Fourth',
            'other': 'Last',
          })}";
```

And to use like this:

```dart
S.of(context).weekOfMonthType(weekOfMonth.toString());
```

**Comment by lzoran** [comment]
Sorry for the delayed response.

> My current approach is to prepend the integer with the letter n.

It looks like a simpler solution. 👍 

> I don't have access to the source code but the solution seems pretty easy. Would be just to handle integers as string instead of ignoring it.

Yes, but unfortunately, that would diverge from the recommended way of usage ([link](http://site.icu-project.org/design/formatting/select)). In case you really need such functionality, you can always fork the generator of the localization files ([intl_utils](https://github.com/localizely/intl_utils) package) and adjust it.

I suggest leaving this issue open, so we can easily monitor interest for such functionality. In case this attracts a significant number of upvotes, then consider extending the current implementation to support integers as well.

**Comment by lzoran** [comment]
Closing this issue because it has been open for some time and without activity.
