### ISSUE TITLE
Trigger the creation of the generated folder

### ISSUE THREAD

**Issue by d-wolf** [localizely/flutter-intl-vscode#85]
Is there a way to trigger the creation of gernerated files (generated/l10n.dart, generated/intl/*) by command-line?

I don't want to check in the generated files into my repository but i would like to do CI with github actions. Now my widget tests are failing: ``` Error when reading 'lib/generated/l10n.dart': No such file or directory```. I would like to run a command which creates the missing files before testing.

**Comment by lzoran** [comment]
Hi @d-wolf,

To generate localization files through the command line, you can use an [intl_utils](https://pub.dev/packages/intl_utils) package.
To check which version of the `intl_utils` package your Flutter Intl extension uses, run `flutter pub global list`.

Hope it helps!

**Comment by d-wolf** [comment]
When i run ```flutter pub global list``` the command line tells me Flutter intl extension uses ```intl_utils 2.4.0```. So I have added ```intl_utils 2.4.0``` to my pubspec.yaml.

Now i can run ```flutter pub run intl_utils:generate``` to create the gernerated files from command line. Exactly what i need.

Thanks for the hint @lzoran!
