### ISSUE TITLE
DateTime format not working

### ISSUE THREAD

**Issue by ghost** [localizely/flutter-intl-vscode#86]
Hi,

I just installed this extension. I just love it.
The issue is, as I'm following the [docs](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) for a first setup, I read about the following `DateTime` example:

```
"commonCurrentDateTime": "Date: {date} Time: {time}",
"@commonCurrentDateTime": {
    "placeholders": {
        "date": {
            "type": "DateTime",
            "format": "yMd"
        },
        "time": {
            "type": "DateTime",
            "format": "Hm"
        }
    }
}
```

The thing is, as I'm try to replicate this in my own code, this doesn't work.
My .arb file:
```
"dayMessage": "Here's your day: {day}",
  "@dayMessage": {
    "description": "...",
    "placeholders": {
      "day": {
        "type": "DateTime",
        "format": "yMd"
      }
    }
  },
```

What I see inside my app, instead, is something like:
`2021-11-11 23:59:59.000`

Why?
How can I specify the date format in my arb file?
I find that very clever, but it doesn't seem to work.

Also, in my code, I'd expect the `S.current.dayMessage` to accept a `DateTime` as an argument, and instead all the arguments are always accepted as `Object`s.

Why?

**Comment by lzoran** [comment]
Hi @luca-venir,

Thanks for reporting this.

This feature is added in the `Flutter Intl 1.17.0` extension for the VS Code. 
Could you check if you are using the appropriate version of the extension?

**Comment by ghost** [comment]
Hi there,

thank you for this quick response.
I confirm that the version I'm using is the `v1.17.0`.

![intl version](https://user-images.githubusercontent.com/84397515/141457505-c2a57322-d698-49ad-a929-80af0aeee9ec.png)

**Comment by lzoran** [comment]
Interesting... 😕 

Could you also check if the appropriate version of the `intl_utils` package is activated globally (it is needed `intl_utils 2.5.1`)?
```
flutter pub global list
```

I don't know exactly what could be the cause of this problem. Maybe re-install of the globally activated `intl_utils` and the extension could help?

- Deactivate `intl_utils`: `flutter pub global deactivate intl_utils`
- Uninstall Flutter Intl extension
- Install Flutter Intl extension
- Restart IDE
- Run generation of the localization code (update one of arb files and save)

**Comment by ghost** [comment]
Thank you again for the quick response.

FYI, here's the result of my `flutter pub global list`:
```
myTerminal/.../myAppFolder$ flutter pub global list
devtools 2.1.1
intl_utils 2.5.1
```

I followed your suggested steps, except that the last one doesn't really work. Now if I run the above command again, I get the same output.

**If I try to modify my arb files by adding a "test" key-value pair, nothing happens**.
What I added:
```
  "test": "test",
  "@test": {
    "description": "test"
  }
```

In a random Widget in the tree I wrote:
```
print(S.of(context).test);
```

I get (obviously) a compilation error.

Am I missing some steps? I'm so sorry if I do. I just re-read and did the steps in the official extension home page, just in case.
If it can help, here's my `flutter_intl` configuration in my `.yaml` file:

```
flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated
```

The weird thing is that now I'm actually unable to add key-value pairs :-1:

**Comment by ghost** [comment]
**update**

Upon further check, there was a comma missing on that `test` key-value pair. I'm sorry. Nonetheless, no error was given and furthermore the `DateTime` formatting issue still persists. There are no other missing commas.

**Comment by lzoran** [comment]
You can find all necessary info related to generating localization code under **Output** window in VS Code.

![vs-code-output-window](https://user-images.githubusercontent.com/15170421/141461820-a32e9c12-0544-4c8a-9557-d2a7fa0378cb.png)

Also, you can manually run generation from the command line: `flutter pub global run intl_utils:generate` (that is what extension does).

**Comment by ghost** [comment]
Thank you!

Here's the output I get:

```
INFO: Generating localization files for the 'sample' project...
INFO: No @@locale or _locale field found in intl_en, assuming 'en' based on the file name.
INFO: No @@locale or _locale field found in intl_it, assuming 'it' based on the file name.
exit code 0
```

Which - I assume - it means everything's OK.
I tried again to check my app - whenever I encounter `DateTime` strings, my localization still accepts a generic `Object` and I still get the full date and time like the following: `2021-11-11 23:59:59`. :cry:

**Comment by ghost** [comment]
Hi again,

I've looked at the generated code and the aforementioned behavior doesn't really surprise me.
The generated code looks like this:

```
/// `Here's your day: {day}`
  String day(Object day) {
    return Intl.message(
      'Here\'s your day: $day',
      name: 'day',
      desc: '',
      args: [day],
    );
  }
```

Indeed this function just gets a generic `Object` and then the string interpolation on the `day` object doesn't properly format the string. Another curious thing is that the `desc` parameter is set to an empty string, where as I added `...` as a description parameter in the `.arb.` file.

**Comment by lzoran** [comment]
Yes, you are right. It looks that generation works well.

The `l10n.dart` should have `dayMessage` method that looks like:
```
  /// `Here's your day: {day}`
  String dayMessage(DateTime day) {
    final DateFormat dayDateFormat = DateFormat.yMd(Intl.getCurrentLocale());
    final String dayString = dayDateFormat.format(day);

    return Intl.message(
      'Here\'s your day: $dayString',
      name: 'dayMessage',
      desc: '...',
      args: [dayString],
    );
  }
```

As you are using the custom `output_dir`, could you check if you are using the right `l10n.dart` file in your project? Maybe it is a copy-paste error. 😕 
```
import 'l10n/generated/l10n.dart';
```

**Comment by ghost** [comment]
Sorry, I was just checking that, I answered you above.

As an addition, here's how I import my files:
`import '../../../l10n/generated/l10n.dart';`

Which means I use relative imports "by-hand" in every file. I guess I'd be receiving a compilation error if Dart wasn't able to find such file because of a similar mistake.

**Comment by ghost** [comment]
If this can help, in my _actual_ project my variable has another name. Here it comes:

```
"youVeSelectedDay": "You've selected data for {day}",
  "@youVeSelected": {
    "description": "`Day` detail label selection in the `Consumption` tab",
    "placeholders": {
      "day": {
        "type": "DateTime",
        "format": "yMd"
      }
    }
  }
```

And in my project I invoke:
```
S.current.youVeSelectedDay(day)
```

with the same results, as the generated code looks like this:
```
  /// `You've selected data for {day}`
  String youVeSelectedDay(Object day) {
    return Intl.message(
      'You\'ve selected data for $day',
      name: 'youVeSelectedDay',
      desc: '',
      args: [day],
    );
  }
```

**Comment by lzoran** [comment]
Wrong metadata...

Metadata for the string key should have the same name + prefix `@` (for the string key `youVeSelectedDay` it should be `@youVeSelectedDay`).

```
  "youVeSelectedDay": "You've selected data for {day}",
  "@youVeSelectedDay": {
    "description": "`Day` detail label selection in the `Consumption` tab",
    "placeholders": {
      "day": {
        "type": "DateTime",
        "format": "yMd"
      }
    }
  }
```

**Comment by ghost** [comment]
Well isn't this actually embarassing... The thing is that these errors don't appear in the output console as errors or warnings or infos.

Now I have another issue, if you could help me, as I can't find any documentation on this.

I'd actually want to format my dates as "dd/MM" instead of "yMd". How can I achieve that?

**Comment by lzoran** [comment]
Currently, the Flutter Intl extension supports only predefined date formatting.
More info [doc](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html).

Maybe `Md` would work for you?

Note, the custom formatting is not supported at the moment.

**Comment by ghost** [comment]
Thank you for your assistance.

Unluckily the american date format doesn't work for my client.

I'm sorry if I wasted your time.

What about the "info" message when a key-value pair has no matadata or a "warn" message that a metadata is added with no corresponding key in the same file?
Would that be useful?

**Comment by lzoran** [comment]
I would say that the `Md` is adaptable format to different locales. In other words, it will format `DateTime` propperly for the selected locale code.

Examples:
- English (`en`): `11/12`
- English GB (`en_GB`): `12/11`
- Italian (`it`): `12/11`
- German (`de`): `12.11.`.

**Comment by ghost** [comment]
This is great. Thanks!!!

**Comment by lzoran** [comment]
> What about the "info" message when a key-value pair has no matadata or a "warn" message that a metadata is added with no corresponding key in the same file?
Would that be useful?

I agree that would be useful. I will create a new issue for that purpose.

Thanks for the feedback!
