### ISSUE TITLE
Error on generated files

### ISSUE THREAD

**Issue by kishormainali** [localizely/flutter-intl-vscode#87]
![Screen Shot 2022-01-14 at 12 53 49 PM](https://user-images.githubusercontent.com/33093136/149466072-b41897ac-aa71-431d-8dc0-db562774dbfb.png)
![Screen Shot 2022-01-14 at 12 53 34 PM](https://user-images.githubusercontent.com/33093136/149466096-f6a0e59c-c185-4a26-a45e-377e5f3150d5.png)

**Comment by lzoran** [comment]
Hi @kishor98100,

According to the attached screenshots, I assume that you need to use the null-safe code. 

The Flutter Intl extension checks the version of the environment sdk within the `pubspec.yaml` file and generates the appropriate code according to it.

The example of the `pubspec.yaml` file that will cause generation of the null-safe code:
```
...
environment:
  sdk: ">=2.12.0 <3.0.0"
...
```

**Comment by kishormainali** [comment]
Hi @lzoran i am using flutter version 2.8 but still error exists

<img width="802" alt="Screen Shot 2022-01-17 at 10 17 40 AM" src="https://user-images.githubusercontent.com/33093136/149708456-81a2731f-c880-491f-8b72-f5c6b4bb1063.png">

**Comment by lzoran** [comment]
Hi @kishor98100,

I've tried to reproduce this issue, but without success. On my machine everything works fine. 😕

Could you check the version of the globally activated `intl_utils` package (`flutter pub global list`)?
This is the package that the Flutter Intl extension uses for the generation of localization code (the `intl_utils ^2.0.0` generates null-safe code).

Also, could you check the Output window within your VS Code?
Maybe there are some useful logs.

![vs-code-output-window](https://user-images.githubusercontent.com/15170421/149741297-827b0efe-49c2-4868-a09a-141e5282f7af.png)

**Comment by kishormainali** [comment]
@lzoran i cleaned my pub cache then re run flutter pub run intl_utils:generate and it works fine. thanks for the help.
