### ISSUE TITLE
intl package

### ISSUE THREAD

**Issue by miguelpruivo** [localizely/flutter-intl-vscode#88]
**Question:** does this package completely replaces dependency of the Dart's intl package?

**Comment by lzoran** [comment]
Hi @miguelpruivo,

Not sure I understand the question.  😕 

This is the repository of the [Flutter Intl](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl), the extension that generates boilerplate code for the [intl](https://pub.dev/packages/intl) package. Under the hood, this extension relies on the [intl_utils](https://pub.dev/packages/intl_utils) package. None of them replaces the mentioned intl package, but generate the necessary boilerplate code for it.

Did you notice any flaws in the documentation?

**Comment by miguelpruivo** [comment]
@lzoran probably I didn't make the right question: do I need to add intl dependency to my pubspec.yaml? What happens if I don't? Because it doesn't seem to complain if I use only flutter intl + flutter_localizations.

**Comment by lzoran** [comment]
Hi @miguelpruivo,

According to the Flutter guidelines for internationalization, you should add the `intl` package as a dependency.

However, as the `flutter_localizations` requires the `intl` also, it makes it a [transitive dependency](https://dart.dev/tools/pub/glossary#transitive-dependency). I assume that that is the reason why your IDE does not complain.

**Comment by miguelpruivo** [comment]
That's correct then, understood. Thank you for clarifying. I don't see why the reason then to explicitly use `intl` dependency when using the `flutter_localizations`.
