### ISSUE TITLE
auto-create on save doesn't work

### ISSUE THREAD

**Issue by nero-angela** [localizely/flutter-intl-vscode#89]
Thanks for making such a great extension.
I was facing a problem that the auto-generation function did not work even after editing the arb file and saving it.

things I've tried
1. After adding the `intl_util` package to the `pubspec.yaml` file, manually running it via `flutter pub run intl_utils:generate` command to enable generation was successful. However, it is not automatically created on save.
2. Reinstall extension → Fail

Is there any way to fix it?

**Comment by lzoran** [comment]
Hi @nero-angela,

To enable the Flutter Intl extension in the VS Code, you should run the "Flutter Intl: Initialize" command (e.g. open Command Palette with `Ctrl + Shift + P` and search for the "Flutter Intl: Initialize").

Initialized Flutter Intl extension should update the `pubspec.yaml` file.

```
flutter_intl:
  enabled: true
```

Under the "Output" window in the VS Code, you can find useful logs that can help you to find potential errors during localization code generation.

![vs-code-output-window](https://user-images.githubusercontent.com/15170421/149744485-348f478d-4af6-42d5-a20a-e5e1f06f0c0c.png)

Also, the Flutter Intl extension uses a globally activated `intl_utils` package for generation (e.g. to check the version of the installed package run `flutter pub global list`).

> Reinstall extension → Fail

As this should not happen, could you share more details regarding this?

**Comment by nero-angela** [comment]
Hi @lzoran 

When I checked the log using the way you mentioned, the output is as follows.
```
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-2.8.0/lib/dart/ast/token.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
```

I downgraded Flutter a while ago, but the cache is still there and seems to be causing the above issue.
So I cleared the cache with the `flutter pub cache repair` command and the problem was solved.

Thanks for your kind reply.
You saved my time 👍

**Comment by nero-angela** [comment]
> Reinstall extension → Fail

This part meant that the reinstallation did not solve the problem. Now that the issue is resolved, I will close the issue. thank you.
