### ISSUE TITLE
Not generate when key is "continue"

### ISSUE THREAD

**Issue by pro100andrey** [localizely/flutter-intl-vscode#91]
For example:
File name is `intl_en.arb`

```json
{
  "continue": "Продолжить"
}
```

 VSCode output:

```
INFO: Generating localization files for the 'core' project...
INFO: Failed to format 'l10n.dart' file.
Error in parsing /Users/.../packages/core/lib/generated/l10n.dart, no messages extracted.
ERROR: Failed to generate localization files.
Invalid argument(s): Parsing errors in /Users/...packages/core/lib/generated/l10n.dart
pub finished with exit code 2
exit code 2
```

For example: if change the key 'continue' into 'goOn'

``` json
{
    "goOn": "Продолжить"
}
```
all works!

**Comment by lzoran** [comment]
Hi @pro100andrey,

The `continue` is a reserved keyword in Dart, and as such, it can't be used as an identifier. The same applies to other reserved keywords like `for`, `break`, `return`, and similar.

You can find more info [here](https://dart.dev/guides/language/language-tour#keywords).

Maybe renaming (e.g. `goOn`) or adding a prefix (e.g. `commonContinue`) to the string key would be the right way to go.

**Comment by pro100andrey** [comment]
@lzoran Thanks for your answer.

In my opinion,  [flutter-intl-vscode](https://github.com/localizely/flutter-intl-vscode) documentation should contain a paragraph about keywords, because this is unpredictable for users.

Thanks!
