### ISSUE TITLE
Haven't option "Extract to ARB files" in VSCode

### ISSUE THREAD

**Issue by booooohdan** [localizely/flutter-intl-vscode#92]
I installed the extension "Flutter Intl", but haven't option Extract to ARB files

![444](https://user-images.githubusercontent.com/30977443/161441627-50cdedcb-8caa-4a08-b6a0-09d95c2f3bad.png)
No issues in "flutter doctor"
Here is my repo: https://github.com/booooohdan/flutter_wt_versus/tree/feature/Implement_comparison_for_tanks%2C_helicopters_and_fleet

**Comment by lzoran** [comment]
Hi @booooohdan,

I've checked the attached project. It seems that you didn't initialize the Flutter Intl extension (`Ctrl + Shift + P` > `Flutter Intl: Initialize`). 

Note that the initialized Flutter Intl extension will generate the necessary localization files that you can use later in your code.

**Comment by Frezyx** [comment]
> Hi @booooohdan,
> 
> I've checked the attached project. It seems that you didn't initialize the Flutter Intl extension (`Ctrl + Shift + P` > `Flutter Intl: Initialize`).
> 
> Note that the initialized Flutter Intl extension will generate the necessary localization files that you can use later in your code.

Hello ! <br> I'm getting this error after update to 1.18.2 <br> when i try ```Ctrl + Shift + P > Flutter Intl: Initialize``` <br>
<img width="320" alt="image" src="https://user-images.githubusercontent.com/40857927/161696790-0ae140af-d1c3-4d7e-9d95-6cb2b669fa31.png">

**Comment by lzoran** [comment]
Hi @Frezyx,

Thanks for reporting this!

I've tried to reproduce the reported error, but without success. Everything works fine on my machine (Windows 11, VS Code 1.66.0).

Maybe restarting the IDE could help?
If the error still occurs after the restart, could you provide us with more details about your IDE version and upgrade steps so that we can more easily find the cause of the problem?

**Comment by emvaized** [comment]
Hi @lzoran 
I'm currently facing the same problem – all Intl's actions in the Command pallete result in the same error "command not found". IDE restart didn't help.

Versions:
VS Code 1.66.0 (Universal)
Flutter Intl 1.18.2

Running `flutter pub run intl_utils:generate` returns this:
> Could not find package "intl_utils". Did you forget to add a dependency?
> pub finished with exit code 65

I also tried running `flutter pub cache repair`, and ended up getting these errors:

<details> 
  <summary>Console output </summary>
  
> Reactivating intl_utils 2.6.1...
> Building package executables...
> Failed to build intl_utils:localizely_upload_main:
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/config_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/credentials_config.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/pubspec_config.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/constants/constants.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/api/api_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/service/service.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/service/service_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/file_utils.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/utils.dart'.
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:6:8: Error: Not found: 'package:intl_utils/src/config/config_exception.dart'
> import 'package:intl_utils/src/config/config_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:7:8: Error: Not found: 'package:intl_utils/src/config/credentials_config.dart'
> import 'package:intl_utils/src/config/credentials_config.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:8:8: Error: Not found: 'package:intl_utils/src/config/pubspec_config.dart'
> import 'package:intl_utils/src/config/pubspec_config.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:9:8: Error: Not found: 'package:intl_utils/src/constants/constants.dart'
> import 'package:intl_utils/src/constants/constants.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:10:8: Error: Not found: 'package:intl_utils/src/localizely/api/api_exception.dart'
> import 'package:intl_utils/src/localizely/api/api_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:11:8: Error: Not found: 'package:intl_utils/src/localizely/service/service.dart'
> import 'package:intl_utils/src/localizely/service/service.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:12:8: Error: Not found: 'package:intl_utils/src/localizely/service/service_exception.dart'
> import 'package:intl_utils/src/localizely/service/service_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:13:8: Error: Not found: 'package:intl_utils/src/utils/file_utils.dart'
> import 'package:intl_utils/src/utils/file_utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:14:8: Error: Not found: 'package:intl_utils/src/utils/utils.dart'
> import 'package:intl_utils/src/utils/utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:31:27: Error: Method not found: 'PubspecConfig'.
>     final pubspecConfig = PubspecConfig();
>                           ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:32:31: Error: Method not found: 'CredentialsConfig'.
>     final credentialsConfig = CredentialsConfig();
>                               ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:57:45: Error: Getter not found: 'defaultArbDir'.
>         defaultsTo: pubspecConfig.arbDir ?? defaultArbDir,
>                                             ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:64:49: Error: Getter not found: 'defaultMainLocale'.
>         defaultsTo: pubspecConfig.mainLocale ?? defaultMainLocale,
>                                                 ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:78:13: Error: Getter not found: 'defaultUploadOverwrite'.
>             defaultUploadOverwrite,
>             ^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:86:13: Error: Getter not found: 'defaultUploadAsReviewed'.
>             defaultUploadAsReviewed,
>             ^^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:116:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:123:96: Error: Method not found: 'getLocalizelyCredentialsFilePath'.
>           "Argument 'api-token' was not provided, nor 'api_token' config was set within the '${getLocalizelyCredentialsFilePath()}' file.");
>                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:122:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:126:10: Error: Method not found: 'isValidLocale'.
>     if (!isValidLocale(mainLocale)) {
>          ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:127:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:132:11: Error: Getter not found: 'LocalizelyService'.
>     await LocalizelyService.uploadMainArbFile(
>           ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:144:5: Error: Method not found: 'exitWithError'.
>     exitWithError('${e.message}\n\n${argParser.usage}');
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:145:8: Error: 'ConfigException' isn't a type.
>   } on ConfigException catch (e) {
>        ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:146:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:147:8: Error: 'ServiceException' isn't a type.
>   } on ServiceException catch (e) {
>        ^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:148:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:149:8: Error: 'ApiException' isn't a type.
>   } on ApiException catch (e) {
>        ^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:150:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.getFormattedMessage());
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:152:5: Error: Method not found: 'exitWithError'.
>     exitWithError('Failed to upload the main ARB file on Localizely.\n$e');
>     ^^^^^^^^^^^^^
> Failed to build intl_utils:generate:
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/intl_utils.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/generator/generator_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/utils.dart'.
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:3:8: Error: Not found: 'package:intl_utils/intl_utils.dart'
> import 'package:intl_utils/intl_utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:4:8: Error: Not found: 'package:intl_utils/src/generator/generator_exception.dart'
> import 'package:intl_utils/src/generator/generator_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:5:8: Error: Not found: 'package:intl_utils/src/utils/utils.dart'
> import 'package:intl_utils/src/utils/utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:9:21: Error: Method not found: 'Generator'.
>     var generator = Generator();
>                     ^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:11:8: Error: 'GeneratorException' isn't a type.
>   } on GeneratorException catch (e) {
>        ^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:12:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/generate.dart:14:5: Error: Method not found: 'exitWithError'.
>     exitWithError('Failed to generate localization files.\n$e');
>     ^^^^^^^^^^^^^
> Failed to build intl_utils:localizely_download:
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/config_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/credentials_config.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/pubspec_config.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/constants/constants.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/api/api_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/service/service.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/service/service_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/file_utils.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/utils.dart'.
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:6:8: Error: Not found: 'package:intl_utils/src/config/config_exception.dart'
> import 'package:intl_utils/src/config/config_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:7:8: Error: Not found: 'package:intl_utils/src/config/credentials_config.dart'
> import 'package:intl_utils/src/config/credentials_config.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:8:8: Error: Not found: 'package:intl_utils/src/config/pubspec_config.dart'
> import 'package:intl_utils/src/config/pubspec_config.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:9:8: Error: Not found: 'package:intl_utils/src/constants/constants.dart'
> import 'package:intl_utils/src/constants/constants.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:10:8: Error: Not found: 'package:intl_utils/src/localizely/api/api_exception.dart'
> import 'package:intl_utils/src/localizely/api/api_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:11:8: Error: Not found: 'package:intl_utils/src/localizely/service/service.dart'
> import 'package:intl_utils/src/localizely/service/service.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:12:8: Error: Not found: 'package:intl_utils/src/localizely/service/service_exception.dart'
> import 'package:intl_utils/src/localizely/service/service_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:13:8: Error: Not found: 'package:intl_utils/src/utils/file_utils.dart'
> import 'package:intl_utils/src/utils/file_utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:14:8: Error: Not found: 'package:intl_utils/src/utils/utils.dart'
> import 'package:intl_utils/src/utils/utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:28:27: Error: Method not found: 'PubspecConfig'.
>     final pubspecConfig = PubspecConfig();
>                           ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:29:31: Error: Method not found: 'CredentialsConfig'.
>     final credentialsConfig = CredentialsConfig();
>                               ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:54:45: Error: Getter not found: 'defaultArbDir'.
>         defaultsTo: pubspecConfig.arbDir ?? defaultArbDir,
>                                             ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:69:13: Error: Getter not found: 'defaultDownloadEmptyAs'.
>             defaultDownloadEmptyAs,
>             ^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:91:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:98:96: Error: Method not found: 'getLocalizelyCredentialsFilePath'.
>           "Argument 'api-token' was not provided, nor 'api_token' config was set within the '${getLocalizelyCredentialsFilePath()}' file.");
>                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:97:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:101:10: Error: Method not found: 'isValidDownloadEmptyAsParam'.
>     if (!isValidDownloadEmptyAsParam(downloadEmptyAs)) {
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:102:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:107:11: Error: Getter not found: 'LocalizelyService'.
>     await LocalizelyService.download(projectId!, apiToken!, arbDir,
>           ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:110:5: Error: Method not found: 'exitWithError'.
>     exitWithError('${e.message}\n\n${argParser.usage}');
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:111:8: Error: 'ConfigException' isn't a type.
>   } on ConfigException catch (e) {
>        ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:112:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:113:8: Error: 'ServiceException' isn't a type.
>   } on ServiceException catch (e) {
>        ^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:114:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:115:8: Error: 'ApiException' isn't a type.
>   } on ApiException catch (e) {
>        ^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:116:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.getFormattedMessage());
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_download.dart:118:5: Error: Method not found: 'exitWithError'.
>     exitWithError('Failed to download ARB files from Localizely.\n$e');
>     ^^^^^^^^^^^^^
> Failed to reactivate intl_utils 2.6.1: Failed to build intl_utils:localizely_upload_main:
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/config_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/credentials_config.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/config/pubspec_config.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/constants/constants.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/api/api_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/service/service.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/localizely/service/service_exception.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/file_utils.dart'.
> Error: Couldn't resolve the package 'intl_utils' in 'package:intl_utils/src/utils/utils.dart'.
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:6:8: Error: Not found: 'package:intl_utils/src/config/config_exception.dart'
> import 'package:intl_utils/src/config/config_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:7:8: Error: Not found: 'package:intl_utils/src/config/credentials_config.dart'
> import 'package:intl_utils/src/config/credentials_config.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:8:8: Error: Not found: 'package:intl_utils/src/config/pubspec_config.dart'
> import 'package:intl_utils/src/config/pubspec_config.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:9:8: Error: Not found: 'package:intl_utils/src/constants/constants.dart'
> import 'package:intl_utils/src/constants/constants.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:10:8: Error: Not found: 'package:intl_utils/src/localizely/api/api_exception.dart'
> import 'package:intl_utils/src/localizely/api/api_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:11:8: Error: Not found: 'package:intl_utils/src/localizely/service/service.dart'
> import 'package:intl_utils/src/localizely/service/service.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:12:8: Error: Not found: 'package:intl_utils/src/localizely/service/service_exception.dart'
> import 'package:intl_utils/src/localizely/service/service_exception.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:13:8: Error: Not found: 'package:intl_utils/src/utils/file_utils.dart'
> import 'package:intl_utils/src/utils/file_utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:14:8: Error: Not found: 'package:intl_utils/src/utils/utils.dart'
> import 'package:intl_utils/src/utils/utils.dart';
>        ^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:31:27: Error: Method not found: 'PubspecConfig'.
>     final pubspecConfig = PubspecConfig();
>                           ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:32:31: Error: Method not found: 'CredentialsConfig'.
>     final credentialsConfig = CredentialsConfig();
>                               ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:57:45: Error: Getter not found: 'defaultArbDir'.
>         defaultsTo: pubspecConfig.arbDir ?? defaultArbDir,
>                                             ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:64:49: Error: Getter not found: 'defaultMainLocale'.
>         defaultsTo: pubspecConfig.mainLocale ?? defaultMainLocale,
>                                                 ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:78:13: Error: Getter not found: 'defaultUploadOverwrite'.
>             defaultUploadOverwrite,
>             ^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:86:13: Error: Getter not found: 'defaultUploadAsReviewed'.
>             defaultUploadAsReviewed,
>             ^^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:116:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:123:96: Error: Method not found: 'getLocalizelyCredentialsFilePath'.
>           "Argument 'api-token' was not provided, nor 'api_token' config was set within the '${getLocalizelyCredentialsFilePath()}' file.");
>                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:122:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:126:10: Error: Method not found: 'isValidLocale'.
>     if (!isValidLocale(mainLocale)) {
>          ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:127:13: Error: Method not found: 'ConfigException'.
>       throw ConfigException(
>             ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:132:11: Error: Getter not found: 'LocalizelyService'.
>     await LocalizelyService.uploadMainArbFile(
>           ^^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:144:5: Error: Method not found: 'exitWithError'.
>     exitWithError('${e.message}\n\n${argParser.usage}');
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:145:8: Error: 'ConfigException' isn't a type.
>   } on ConfigException catch (e) {
>        ^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:146:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:147:8: Error: 'ServiceException' isn't a type.
>   } on ServiceException catch (e) {
>        ^^^^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:148:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.message);
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:149:8: Error: 'ApiException' isn't a type.
>   } on ApiException catch (e) {
>        ^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:150:5: Error: Method not found: 'exitWithError'.
>     exitWithError(e.getFormattedMessage());
>     ^^^^^^^^^^^^^
> ../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.1/bin/localizely_upload_main.dart:152:5: Error: Method not found: 'exitWithError'.
>     exitWithError('Failed to upload the main ARB file on Localizely.\n$e');
>     ^^^^^^^^^^^^^
> Failed to reactivate 1 package:
> - intl_utils
> pub finished with exit code 69

</details>

**Comment by lzoran** [comment]
Hi @emvaized,

I'll take a closer look at this issue.
In the meantime, could you check if re-activating the `intl_utils` package solves the problem?

1. Re-activate `intl_utils`
```
flutter pub global deactivate intl_utils
flutter pub global activate intl_utils
```

2. Invoke one of Flutter Intl commands (e.g. update the arb file and `Ctrl + S`)

**Comment by emvaized** [comment]
The first command returns this:

> No active package intl_utils.
> pub finished with exit code 65

The second one runs without errors, but Intl commands still result in error shown above.

**Comment by lzoran** [comment]
@emvaized, thanks for the check.

According to the attached logs, I would say that the problem is in the cache, not in the Flutter Intl extension 😕.

The Flutter Intl extension relies on the `intl_utils` package for generating the localization files. It just triggers generation whenever you update arb files. In case you are blocked, you can also manually run generation with the: `flutter pub global run intl_utils:generate`.

As I'm not able to reproduce the reported issue, maybe reinstalling the Flutter Intl extension might help? If the error still occurs, could you provide us with more details regarding your IDE version, Flutter version, and OS?
