### ISSUE TITLE
Failed to activate Flutter Intl extension

### ISSUE THREAD

**Issue by techpool** [localizely/flutter-intl-vscode#94]
For a few weeks I've been seeing this pop up
![image](https://user-images.githubusercontent.com/13390045/177897159-5a6a9e34-cdb7-4486-bea9-7b819a0ff166.png)

The devtools also doesn't give out much info:
![image](https://user-images.githubusercontent.com/13390045/177897222-5f3b7e1f-9c89-45d3-a9a8-193cfd250754.png)

All of this is not allowing me to load the extension. Not sure if I am doing something incorrectly. I have tried reloading the extension, uninstalling and installing the extension and also at the same time installing an older version. Did something change in VSCode because of which it might be triggering this?

**Comment by lzoran** [comment]
Hi @techpool,

I've tried to reproduce the reported issue, but without success 😞.
Everything works fine on my machine.

**OS:**
Windows 11

**Flutter:**
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (8 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2

**VS Code:**
Version: 1.69.0 (system setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Flutter Intl extension:**
v1.18.2

Not sure what might cause this error 😕.
Could you provide us with more details (OS version, VS Code version, Flutter version, Flutter Intl extension version), so we can try to reproduce it in a similar environment?
Also, does this error appear for all Flutter projects? Does it work with this [sample project](https://github.com/localizely/flutter-intl-plugin-sample-app)?

**Comment by techpool** [comment]
Hey @lzoran! Thanks for the tip! It actually works if I open the project individually! Probably something is wrong in that workspace itself. Thanks a lot again for the help, I'll close this issue.

**Comment by fullflash** [comment]
same here. Failed to activate Flutter Intl extension.

**Comment by lzoran** [comment]
@fullflash, thanks for reporting this.

Could you please provide more information (OS version, VS Code version, Flutter version, Flutter Intl extension version, sample project where activation fails) as this problem is not easily reproducible?

**Comment by czaefferer** [comment]
I ran into the same problem (Failed to activate Flutter Intl extension), in my case the problem was a project in the workspace where the underlying folder in the filesystem had been deleted. After removing that project from the workspace the extension worked again.
Not sure if it worth fixing, but just in case anyone else with the same situation stumbles over this thread.
